spring.application.name=be-room-rental

server.servlet.context-path=${BE_URI_API}
server.port=8080

spring.mongodb.uri=${MONGODB_URI}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.access-expiration=${JWT_ACCESS_EXPIRATION}
app.jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION}

cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

app.admin.username=${ADMIN_USERNAME}
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

app.frontend.domain=${FE_DOMAIN}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.jackson.property-naming-strategy=SNAKE_CASE
