#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jun 30 12:44:38 ICT 2026
maven-metadata-spring-milestones.xml.lastUpdated=1782798278366
maven-metadata-spring-milestones.xml.error=
maven-metadata-central.xml.lastUpdated=1782798278368
